// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Libvirt
{
    public partial class CloudInitDisk : Pulumi.CustomResource
    {
        [Output("metaData")]
        public Output<string?> MetaData { get; private set; } = null!;

        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        [Output("networkConfig")]
        public Output<string?> NetworkConfig { get; private set; } = null!;

        [Output("pool")]
        public Output<string?> Pool { get; private set; } = null!;

        [Output("userData")]
        public Output<string?> UserData { get; private set; } = null!;


        /// <summary>
        /// Create a CloudInitDisk resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public CloudInitDisk(string name, CloudInitDiskArgs? args = null, CustomResourceOptions? options = null)
            : base("libvirt:index/cloudInitDisk:CloudInitDisk", name, args ?? new CloudInitDiskArgs(), MakeResourceOptions(options, ""))
        {
        }

        private CloudInitDisk(string name, Input<string> id, CloudInitDiskState? state = null, CustomResourceOptions? options = null)
            : base("libvirt:index/cloudInitDisk:CloudInitDisk", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing CloudInitDisk resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static CloudInitDisk Get(string name, Input<string> id, CloudInitDiskState? state = null, CustomResourceOptions? options = null)
        {
            return new CloudInitDisk(name, id, state, options);
        }
    }

    public sealed class CloudInitDiskArgs : Pulumi.ResourceArgs
    {
        [Input("metaData")]
        public Input<string>? MetaData { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("networkConfig")]
        public Input<string>? NetworkConfig { get; set; }

        [Input("pool")]
        public Input<string>? Pool { get; set; }

        [Input("userData")]
        public Input<string>? UserData { get; set; }

        public CloudInitDiskArgs()
        {
        }
    }

    public sealed class CloudInitDiskState : Pulumi.ResourceArgs
    {
        [Input("metaData")]
        public Input<string>? MetaData { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("networkConfig")]
        public Input<string>? NetworkConfig { get; set; }

        [Input("pool")]
        public Input<string>? Pool { get; set; }

        [Input("userData")]
        public Input<string>? UserData { get; set; }

        public CloudInitDiskState()
        {
        }
    }
}
