// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Libvirt
{
    public static class GetNetworkDNSHostTemplate
    {
        public static Task<GetNetworkDNSHostTemplateResult> InvokeAsync(GetNetworkDNSHostTemplateArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetNetworkDNSHostTemplateResult>("libvirt:index/getNetworkDNSHostTemplate:getNetworkDNSHostTemplate", args ?? new GetNetworkDNSHostTemplateArgs(), options.WithVersion());
    }


    public sealed class GetNetworkDNSHostTemplateArgs : Pulumi.InvokeArgs
    {
        [Input("hostname", required: true)]
        public string Hostname { get; set; } = null!;

        [Input("ip", required: true)]
        public string Ip { get; set; } = null!;

        public GetNetworkDNSHostTemplateArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetNetworkDNSHostTemplateResult
    {
        public readonly string Hostname;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string Ip;
        public readonly ImmutableDictionary<string, string> Rendered;

        [OutputConstructor]
        private GetNetworkDNSHostTemplateResult(
            string hostname,

            string id,

            string ip,

            ImmutableDictionary<string, string> rendered)
        {
            Hostname = hostname;
            Id = id;
            Ip = ip;
            Rendered = rendered;
        }
    }
}
