// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Libvirt
{
    public partial class Volume : Pulumi.CustomResource
    {
        [Output("baseVolumeId")]
        public Output<string?> BaseVolumeId { get; private set; } = null!;

        [Output("baseVolumeName")]
        public Output<string?> BaseVolumeName { get; private set; } = null!;

        [Output("baseVolumePool")]
        public Output<string?> BaseVolumePool { get; private set; } = null!;

        [Output("format")]
        public Output<string> Format { get; private set; } = null!;

        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        [Output("pool")]
        public Output<string?> Pool { get; private set; } = null!;

        [Output("size")]
        public Output<int> Size { get; private set; } = null!;

        [Output("source")]
        public Output<string?> Source { get; private set; } = null!;

        [Output("xml")]
        public Output<Outputs.VolumeXml?> Xml { get; private set; } = null!;


        /// <summary>
        /// Create a Volume resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Volume(string name, VolumeArgs? args = null, CustomResourceOptions? options = null)
            : base("libvirt:index/volume:Volume", name, args ?? new VolumeArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Volume(string name, Input<string> id, VolumeState? state = null, CustomResourceOptions? options = null)
            : base("libvirt:index/volume:Volume", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Volume resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Volume Get(string name, Input<string> id, VolumeState? state = null, CustomResourceOptions? options = null)
        {
            return new Volume(name, id, state, options);
        }
    }

    public sealed class VolumeArgs : Pulumi.ResourceArgs
    {
        [Input("baseVolumeId")]
        public Input<string>? BaseVolumeId { get; set; }

        [Input("baseVolumeName")]
        public Input<string>? BaseVolumeName { get; set; }

        [Input("baseVolumePool")]
        public Input<string>? BaseVolumePool { get; set; }

        [Input("format")]
        public Input<string>? Format { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("pool")]
        public Input<string>? Pool { get; set; }

        [Input("size")]
        public Input<int>? Size { get; set; }

        [Input("source")]
        public Input<string>? Source { get; set; }

        [Input("xml")]
        public Input<Inputs.VolumeXmlArgs>? Xml { get; set; }

        public VolumeArgs()
        {
        }
    }

    public sealed class VolumeState : Pulumi.ResourceArgs
    {
        [Input("baseVolumeId")]
        public Input<string>? BaseVolumeId { get; set; }

        [Input("baseVolumeName")]
        public Input<string>? BaseVolumeName { get; set; }

        [Input("baseVolumePool")]
        public Input<string>? BaseVolumePool { get; set; }

        [Input("format")]
        public Input<string>? Format { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("pool")]
        public Input<string>? Pool { get; set; }

        [Input("size")]
        public Input<int>? Size { get; set; }

        [Input("source")]
        public Input<string>? Source { get; set; }

        [Input("xml")]
        public Input<Inputs.VolumeXmlGetArgs>? Xml { get; set; }

        public VolumeState()
        {
        }
    }
}
