// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Libvirt.Outputs
{

    [OutputType]
    public sealed class DomainConsole
    {
        public readonly string? SourceHost;
        public readonly string? SourcePath;
        public readonly string? SourceService;
        public readonly string TargetPort;
        public readonly string? TargetType;
        public readonly string Type;

        [OutputConstructor]
        private DomainConsole(
            string? sourceHost,

            string? sourcePath,

            string? sourceService,

            string targetPort,

            string? targetType,

            string type)
        {
            SourceHost = sourceHost;
            SourcePath = sourcePath;
            SourceService = sourceService;
            TargetPort = targetPort;
            TargetType = targetType;
            Type = type;
        }
    }
}
