// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Libvirt.Outputs
{

    [OutputType]
    public sealed class DomainGraphics
    {
        public readonly bool? Autoport;
        public readonly string? ListenAddress;
        public readonly string? ListenType;
        public readonly string? Type;

        [OutputConstructor]
        private DomainGraphics(
            bool? autoport,

            string? listenAddress,

            string? listenType,

            string? type)
        {
            Autoport = autoport;
            ListenAddress = listenAddress;
            ListenType = listenType;
            Type = type;
        }
    }
}
