// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package libvirt

import (
	"reflect"

	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

type CloudInitDisk struct {
	pulumi.CustomResourceState

	MetaData      pulumi.StringPtrOutput `pulumi:"metaData"`
	Name          pulumi.StringOutput    `pulumi:"name"`
	NetworkConfig pulumi.StringPtrOutput `pulumi:"networkConfig"`
	Pool          pulumi.StringPtrOutput `pulumi:"pool"`
	UserData      pulumi.StringPtrOutput `pulumi:"userData"`
}

// NewCloudInitDisk registers a new resource with the given unique name, arguments, and options.
func NewCloudInitDisk(ctx *pulumi.Context,
	name string, args *CloudInitDiskArgs, opts ...pulumi.ResourceOption) (*CloudInitDisk, error) {
	if args == nil {
		args = &CloudInitDiskArgs{}
	}
	var resource CloudInitDisk
	err := ctx.RegisterResource("libvirt:index/cloudInitDisk:CloudInitDisk", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetCloudInitDisk gets an existing CloudInitDisk resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetCloudInitDisk(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *CloudInitDiskState, opts ...pulumi.ResourceOption) (*CloudInitDisk, error) {
	var resource CloudInitDisk
	err := ctx.ReadResource("libvirt:index/cloudInitDisk:CloudInitDisk", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering CloudInitDisk resources.
type cloudInitDiskState struct {
	MetaData      *string `pulumi:"metaData"`
	Name          *string `pulumi:"name"`
	NetworkConfig *string `pulumi:"networkConfig"`
	Pool          *string `pulumi:"pool"`
	UserData      *string `pulumi:"userData"`
}

type CloudInitDiskState struct {
	MetaData      pulumi.StringPtrInput
	Name          pulumi.StringPtrInput
	NetworkConfig pulumi.StringPtrInput
	Pool          pulumi.StringPtrInput
	UserData      pulumi.StringPtrInput
}

func (CloudInitDiskState) ElementType() reflect.Type {
	return reflect.TypeOf((*cloudInitDiskState)(nil)).Elem()
}

type cloudInitDiskArgs struct {
	MetaData      *string `pulumi:"metaData"`
	Name          *string `pulumi:"name"`
	NetworkConfig *string `pulumi:"networkConfig"`
	Pool          *string `pulumi:"pool"`
	UserData      *string `pulumi:"userData"`
}

// The set of arguments for constructing a CloudInitDisk resource.
type CloudInitDiskArgs struct {
	MetaData      pulumi.StringPtrInput
	Name          pulumi.StringPtrInput
	NetworkConfig pulumi.StringPtrInput
	Pool          pulumi.StringPtrInput
	UserData      pulumi.StringPtrInput
}

func (CloudInitDiskArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*cloudInitDiskArgs)(nil)).Elem()
}
