// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package libvirt

import (
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

func GetNetworkDNSHostTemplate(ctx *pulumi.Context, args *GetNetworkDNSHostTemplateArgs, opts ...pulumi.InvokeOption) (*GetNetworkDNSHostTemplateResult, error) {
	var rv GetNetworkDNSHostTemplateResult
	err := ctx.Invoke("libvirt:index/getNetworkDNSHostTemplate:getNetworkDNSHostTemplate", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getNetworkDNSHostTemplate.
type GetNetworkDNSHostTemplateArgs struct {
	Hostname string `pulumi:"hostname"`
	Ip       string `pulumi:"ip"`
}

// A collection of values returned by getNetworkDNSHostTemplate.
type GetNetworkDNSHostTemplateResult struct {
	Hostname string `pulumi:"hostname"`
	// The provider-assigned unique ID for this managed resource.
	Id       string            `pulumi:"id"`
	Ip       string            `pulumi:"ip"`
	Rendered map[string]string `pulumi:"rendered"`
}
