// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface DomainBootDevice {
    devs?: string[];
}

export interface DomainConsole {
    sourceHost?: string;
    sourcePath?: string;
    sourceService?: string;
    targetPort: string;
    targetType?: string;
    type: string;
}

export interface DomainCpu {
    mode: string;
}

export interface DomainDisk {
    blockDevice?: string;
    file?: string;
    scsi?: boolean;
    url?: string;
    volumeId?: string;
    wwn?: string;
}

export interface DomainFilesystem {
    accessmode?: string;
    readonly?: boolean;
    source: string;
    target: string;
}

export interface DomainGraphics {
    autoport?: boolean;
    listenAddress?: string;
    listenType?: string;
    type?: string;
}

export interface DomainNetworkInterface {
    addresses: string[];
    bridge?: string;
    hostname: string;
    mac: string;
    macvtap?: string;
    networkId: string;
    networkName: string;
    passthrough?: string;
    vepa?: string;
    waitForLease?: boolean;
}

export interface DomainNvram {
    file: string;
    template?: string;
}

export interface DomainVideo {
    type?: string;
}

export interface DomainXml {
    xslt?: string;
}

export interface NetworkDhcp {
    enabled?: boolean;
}

export interface NetworkDns {
    enabled?: boolean;
    forwarders?: outputs.NetworkDnsForwarder[];
    hosts?: outputs.NetworkDnsHost[];
    localOnly?: boolean;
    srvs?: outputs.NetworkDnsSrv[];
}

export interface NetworkDnsForwarder {
    address?: string;
    domain?: string;
}

export interface NetworkDnsHost {
    hostname?: string;
    ip?: string;
}

export interface NetworkDnsSrv {
    domain?: string;
    port?: string;
    priority?: string;
    protocol?: string;
    service?: string;
    target?: string;
    weight?: string;
}

export interface NetworkRoute {
    cidr: string;
    gateway: string;
}

export interface NetworkXml {
    xslt?: string;
}

export interface PoolXml {
    xslt?: string;
}

export interface VolumeXml {
    xslt?: string;
}
