// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Libvirt.Inputs
{

    public sealed class DomainGraphicsArgs : Pulumi.ResourceArgs
    {
        [Input("autoport")]
        public Input<bool>? Autoport { get; set; }

        [Input("listenAddress")]
        public Input<string>? ListenAddress { get; set; }

        [Input("listenType")]
        public Input<string>? ListenType { get; set; }

        [Input("type")]
        public Input<string>? Type { get; set; }

        public DomainGraphicsArgs()
        {
        }
    }
}
