// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Libvirt.Inputs
{

    public sealed class DomainConsoleGetArgs : Pulumi.ResourceArgs
    {
        [Input("sourceHost")]
        public Input<string>? SourceHost { get; set; }

        [Input("sourcePath")]
        public Input<string>? SourcePath { get; set; }

        [Input("sourceService")]
        public Input<string>? SourceService { get; set; }

        [Input("targetPort", required: true)]
        public Input<string> TargetPort { get; set; } = null!;

        [Input("targetType")]
        public Input<string>? TargetType { get; set; }

        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        public DomainConsoleGetArgs()
        {
        }
    }
}
