// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Libvirt.Inputs
{

    public sealed class NetworkDnsArgs : Pulumi.ResourceArgs
    {
        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        [Input("forwarders")]
        private InputList<Inputs.NetworkDnsForwarderArgs>? _forwarders;
        public InputList<Inputs.NetworkDnsForwarderArgs> Forwarders
        {
            get => _forwarders ?? (_forwarders = new InputList<Inputs.NetworkDnsForwarderArgs>());
            set => _forwarders = value;
        }

        [Input("hosts")]
        private InputList<Inputs.NetworkDnsHostArgs>? _hosts;
        public InputList<Inputs.NetworkDnsHostArgs> Hosts
        {
            get => _hosts ?? (_hosts = new InputList<Inputs.NetworkDnsHostArgs>());
            set => _hosts = value;
        }

        [Input("localOnly")]
        public Input<bool>? LocalOnly { get; set; }

        [Input("srvs")]
        private InputList<Inputs.NetworkDnsSrvArgs>? _srvs;
        public InputList<Inputs.NetworkDnsSrvArgs> Srvs
        {
            get => _srvs ?? (_srvs = new InputList<Inputs.NetworkDnsSrvArgs>());
            set => _srvs = value;
        }

        public NetworkDnsArgs()
        {
        }
    }
}
