// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class Domain extends pulumi.CustomResource {
    /**
     * Get an existing Domain resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: DomainState, opts?: pulumi.CustomResourceOptions): Domain {
        return new Domain(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'libvirt:index/domain:Domain';

    /**
     * Returns true if the given object is an instance of Domain.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Domain {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Domain.__pulumiType;
    }

    public readonly arch!: pulumi.Output<string>;
    public readonly autostart!: pulumi.Output<boolean | undefined>;
    public readonly bootDevices!: pulumi.Output<outputs.DomainBootDevice[] | undefined>;
    public readonly cloudinit!: pulumi.Output<string | undefined>;
    public readonly cmdlines!: pulumi.Output<{[key: string]: any}[] | undefined>;
    public readonly consoles!: pulumi.Output<outputs.DomainConsole[] | undefined>;
    public readonly coreosIgnition!: pulumi.Output<string | undefined>;
    public readonly cpu!: pulumi.Output<outputs.DomainCpu | undefined>;
    public readonly description!: pulumi.Output<string | undefined>;
    public readonly disks!: pulumi.Output<outputs.DomainDisk[] | undefined>;
    public readonly emulator!: pulumi.Output<string>;
    public readonly filesystems!: pulumi.Output<outputs.DomainFilesystem[] | undefined>;
    public readonly firmware!: pulumi.Output<string | undefined>;
    public readonly fwCfgName!: pulumi.Output<string | undefined>;
    public readonly graphics!: pulumi.Output<outputs.DomainGraphics | undefined>;
    public readonly initrd!: pulumi.Output<string | undefined>;
    public readonly kernel!: pulumi.Output<string | undefined>;
    public readonly machine!: pulumi.Output<string>;
    public readonly memory!: pulumi.Output<number | undefined>;
    public readonly metadata!: pulumi.Output<string | undefined>;
    public readonly name!: pulumi.Output<string>;
    public readonly networkInterfaces!: pulumi.Output<outputs.DomainNetworkInterface[] | undefined>;
    public readonly nvram!: pulumi.Output<outputs.DomainNvram | undefined>;
    public readonly qemuAgent!: pulumi.Output<boolean | undefined>;
    public readonly running!: pulumi.Output<boolean | undefined>;
    public readonly vcpu!: pulumi.Output<number | undefined>;
    public readonly video!: pulumi.Output<outputs.DomainVideo | undefined>;
    public readonly xml!: pulumi.Output<outputs.DomainXml | undefined>;

    /**
     * Create a Domain resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: DomainArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: DomainArgs | DomainState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (opts && opts.id) {
            const state = argsOrState as DomainState | undefined;
            inputs["arch"] = state ? state.arch : undefined;
            inputs["autostart"] = state ? state.autostart : undefined;
            inputs["bootDevices"] = state ? state.bootDevices : undefined;
            inputs["cloudinit"] = state ? state.cloudinit : undefined;
            inputs["cmdlines"] = state ? state.cmdlines : undefined;
            inputs["consoles"] = state ? state.consoles : undefined;
            inputs["coreosIgnition"] = state ? state.coreosIgnition : undefined;
            inputs["cpu"] = state ? state.cpu : undefined;
            inputs["description"] = state ? state.description : undefined;
            inputs["disks"] = state ? state.disks : undefined;
            inputs["emulator"] = state ? state.emulator : undefined;
            inputs["filesystems"] = state ? state.filesystems : undefined;
            inputs["firmware"] = state ? state.firmware : undefined;
            inputs["fwCfgName"] = state ? state.fwCfgName : undefined;
            inputs["graphics"] = state ? state.graphics : undefined;
            inputs["initrd"] = state ? state.initrd : undefined;
            inputs["kernel"] = state ? state.kernel : undefined;
            inputs["machine"] = state ? state.machine : undefined;
            inputs["memory"] = state ? state.memory : undefined;
            inputs["metadata"] = state ? state.metadata : undefined;
            inputs["name"] = state ? state.name : undefined;
            inputs["networkInterfaces"] = state ? state.networkInterfaces : undefined;
            inputs["nvram"] = state ? state.nvram : undefined;
            inputs["qemuAgent"] = state ? state.qemuAgent : undefined;
            inputs["running"] = state ? state.running : undefined;
            inputs["vcpu"] = state ? state.vcpu : undefined;
            inputs["video"] = state ? state.video : undefined;
            inputs["xml"] = state ? state.xml : undefined;
        } else {
            const args = argsOrState as DomainArgs | undefined;
            inputs["arch"] = args ? args.arch : undefined;
            inputs["autostart"] = args ? args.autostart : undefined;
            inputs["bootDevices"] = args ? args.bootDevices : undefined;
            inputs["cloudinit"] = args ? args.cloudinit : undefined;
            inputs["cmdlines"] = args ? args.cmdlines : undefined;
            inputs["consoles"] = args ? args.consoles : undefined;
            inputs["coreosIgnition"] = args ? args.coreosIgnition : undefined;
            inputs["cpu"] = args ? args.cpu : undefined;
            inputs["description"] = args ? args.description : undefined;
            inputs["disks"] = args ? args.disks : undefined;
            inputs["emulator"] = args ? args.emulator : undefined;
            inputs["filesystems"] = args ? args.filesystems : undefined;
            inputs["firmware"] = args ? args.firmware : undefined;
            inputs["fwCfgName"] = args ? args.fwCfgName : undefined;
            inputs["graphics"] = args ? args.graphics : undefined;
            inputs["initrd"] = args ? args.initrd : undefined;
            inputs["kernel"] = args ? args.kernel : undefined;
            inputs["machine"] = args ? args.machine : undefined;
            inputs["memory"] = args ? args.memory : undefined;
            inputs["metadata"] = args ? args.metadata : undefined;
            inputs["name"] = args ? args.name : undefined;
            inputs["networkInterfaces"] = args ? args.networkInterfaces : undefined;
            inputs["nvram"] = args ? args.nvram : undefined;
            inputs["qemuAgent"] = args ? args.qemuAgent : undefined;
            inputs["running"] = args ? args.running : undefined;
            inputs["vcpu"] = args ? args.vcpu : undefined;
            inputs["video"] = args ? args.video : undefined;
            inputs["xml"] = args ? args.xml : undefined;
        }
        if (!opts) {
            opts = {}
        }

        if (!opts.version) {
            opts.version = utilities.getVersion();
        }
        super(Domain.__pulumiType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Domain resources.
 */
export interface DomainState {
    readonly arch?: pulumi.Input<string>;
    readonly autostart?: pulumi.Input<boolean>;
    readonly bootDevices?: pulumi.Input<pulumi.Input<inputs.DomainBootDevice>[]>;
    readonly cloudinit?: pulumi.Input<string>;
    readonly cmdlines?: pulumi.Input<pulumi.Input<{[key: string]: any}>[]>;
    readonly consoles?: pulumi.Input<pulumi.Input<inputs.DomainConsole>[]>;
    readonly coreosIgnition?: pulumi.Input<string>;
    readonly cpu?: pulumi.Input<inputs.DomainCpu>;
    readonly description?: pulumi.Input<string>;
    readonly disks?: pulumi.Input<pulumi.Input<inputs.DomainDisk>[]>;
    readonly emulator?: pulumi.Input<string>;
    readonly filesystems?: pulumi.Input<pulumi.Input<inputs.DomainFilesystem>[]>;
    readonly firmware?: pulumi.Input<string>;
    readonly fwCfgName?: pulumi.Input<string>;
    readonly graphics?: pulumi.Input<inputs.DomainGraphics>;
    readonly initrd?: pulumi.Input<string>;
    readonly kernel?: pulumi.Input<string>;
    readonly machine?: pulumi.Input<string>;
    readonly memory?: pulumi.Input<number>;
    readonly metadata?: pulumi.Input<string>;
    readonly name?: pulumi.Input<string>;
    readonly networkInterfaces?: pulumi.Input<pulumi.Input<inputs.DomainNetworkInterface>[]>;
    readonly nvram?: pulumi.Input<inputs.DomainNvram>;
    readonly qemuAgent?: pulumi.Input<boolean>;
    readonly running?: pulumi.Input<boolean>;
    readonly vcpu?: pulumi.Input<number>;
    readonly video?: pulumi.Input<inputs.DomainVideo>;
    readonly xml?: pulumi.Input<inputs.DomainXml>;
}

/**
 * The set of arguments for constructing a Domain resource.
 */
export interface DomainArgs {
    readonly arch?: pulumi.Input<string>;
    readonly autostart?: pulumi.Input<boolean>;
    readonly bootDevices?: pulumi.Input<pulumi.Input<inputs.DomainBootDevice>[]>;
    readonly cloudinit?: pulumi.Input<string>;
    readonly cmdlines?: pulumi.Input<pulumi.Input<{[key: string]: any}>[]>;
    readonly consoles?: pulumi.Input<pulumi.Input<inputs.DomainConsole>[]>;
    readonly coreosIgnition?: pulumi.Input<string>;
    readonly cpu?: pulumi.Input<inputs.DomainCpu>;
    readonly description?: pulumi.Input<string>;
    readonly disks?: pulumi.Input<pulumi.Input<inputs.DomainDisk>[]>;
    readonly emulator?: pulumi.Input<string>;
    readonly filesystems?: pulumi.Input<pulumi.Input<inputs.DomainFilesystem>[]>;
    readonly firmware?: pulumi.Input<string>;
    readonly fwCfgName?: pulumi.Input<string>;
    readonly graphics?: pulumi.Input<inputs.DomainGraphics>;
    readonly initrd?: pulumi.Input<string>;
    readonly kernel?: pulumi.Input<string>;
    readonly machine?: pulumi.Input<string>;
    readonly memory?: pulumi.Input<number>;
    readonly metadata?: pulumi.Input<string>;
    readonly name?: pulumi.Input<string>;
    readonly networkInterfaces?: pulumi.Input<pulumi.Input<inputs.DomainNetworkInterface>[]>;
    readonly nvram?: pulumi.Input<inputs.DomainNvram>;
    readonly qemuAgent?: pulumi.Input<boolean>;
    readonly running?: pulumi.Input<boolean>;
    readonly vcpu?: pulumi.Input<number>;
    readonly video?: pulumi.Input<inputs.DomainVideo>;
    readonly xml?: pulumi.Input<inputs.DomainXml>;
}
