// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getNetworkDNSHostTemplate(args: GetNetworkDNSHostTemplateArgs, opts?: pulumi.InvokeOptions): Promise<GetNetworkDNSHostTemplateResult> {
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {
        opts.version = utilities.getVersion();
    }
    return pulumi.runtime.invoke("libvirt:index/getNetworkDNSHostTemplate:getNetworkDNSHostTemplate", {
        "hostname": args.hostname,
        "ip": args.ip,
    }, opts);
}

/**
 * A collection of arguments for invoking getNetworkDNSHostTemplate.
 */
export interface GetNetworkDNSHostTemplateArgs {
    readonly hostname: string;
    readonly ip: string;
}

/**
 * A collection of values returned by getNetworkDNSHostTemplate.
 */
export interface GetNetworkDNSHostTemplateResult {
    readonly hostname: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly ip: string;
    readonly rendered: {[key: string]: string};
}
