// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class Network extends pulumi.CustomResource {
    /**
     * Get an existing Network resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: NetworkState, opts?: pulumi.CustomResourceOptions): Network {
        return new Network(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'libvirt:index/network:Network';

    /**
     * Returns true if the given object is an instance of Network.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Network {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Network.__pulumiType;
    }

    public readonly addresses!: pulumi.Output<string[] | undefined>;
    public readonly autostart!: pulumi.Output<boolean | undefined>;
    public readonly bridge!: pulumi.Output<string>;
    public readonly dhcp!: pulumi.Output<outputs.NetworkDhcp | undefined>;
    public readonly dns!: pulumi.Output<outputs.NetworkDns | undefined>;
    public readonly domain!: pulumi.Output<string | undefined>;
    public readonly mode!: pulumi.Output<string | undefined>;
    public readonly mtu!: pulumi.Output<number | undefined>;
    public readonly name!: pulumi.Output<string>;
    public readonly routes!: pulumi.Output<outputs.NetworkRoute[] | undefined>;
    public readonly xml!: pulumi.Output<outputs.NetworkXml | undefined>;

    /**
     * Create a Network resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: NetworkArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: NetworkArgs | NetworkState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (opts && opts.id) {
            const state = argsOrState as NetworkState | undefined;
            inputs["addresses"] = state ? state.addresses : undefined;
            inputs["autostart"] = state ? state.autostart : undefined;
            inputs["bridge"] = state ? state.bridge : undefined;
            inputs["dhcp"] = state ? state.dhcp : undefined;
            inputs["dns"] = state ? state.dns : undefined;
            inputs["domain"] = state ? state.domain : undefined;
            inputs["mode"] = state ? state.mode : undefined;
            inputs["mtu"] = state ? state.mtu : undefined;
            inputs["name"] = state ? state.name : undefined;
            inputs["routes"] = state ? state.routes : undefined;
            inputs["xml"] = state ? state.xml : undefined;
        } else {
            const args = argsOrState as NetworkArgs | undefined;
            inputs["addresses"] = args ? args.addresses : undefined;
            inputs["autostart"] = args ? args.autostart : undefined;
            inputs["bridge"] = args ? args.bridge : undefined;
            inputs["dhcp"] = args ? args.dhcp : undefined;
            inputs["dns"] = args ? args.dns : undefined;
            inputs["domain"] = args ? args.domain : undefined;
            inputs["mode"] = args ? args.mode : undefined;
            inputs["mtu"] = args ? args.mtu : undefined;
            inputs["name"] = args ? args.name : undefined;
            inputs["routes"] = args ? args.routes : undefined;
            inputs["xml"] = args ? args.xml : undefined;
        }
        if (!opts) {
            opts = {}
        }

        if (!opts.version) {
            opts.version = utilities.getVersion();
        }
        super(Network.__pulumiType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Network resources.
 */
export interface NetworkState {
    readonly addresses?: pulumi.Input<pulumi.Input<string>[]>;
    readonly autostart?: pulumi.Input<boolean>;
    readonly bridge?: pulumi.Input<string>;
    readonly dhcp?: pulumi.Input<inputs.NetworkDhcp>;
    readonly dns?: pulumi.Input<inputs.NetworkDns>;
    readonly domain?: pulumi.Input<string>;
    readonly mode?: pulumi.Input<string>;
    readonly mtu?: pulumi.Input<number>;
    readonly name?: pulumi.Input<string>;
    readonly routes?: pulumi.Input<pulumi.Input<inputs.NetworkRoute>[]>;
    readonly xml?: pulumi.Input<inputs.NetworkXml>;
}

/**
 * The set of arguments for constructing a Network resource.
 */
export interface NetworkArgs {
    readonly addresses?: pulumi.Input<pulumi.Input<string>[]>;
    readonly autostart?: pulumi.Input<boolean>;
    readonly bridge?: pulumi.Input<string>;
    readonly dhcp?: pulumi.Input<inputs.NetworkDhcp>;
    readonly dns?: pulumi.Input<inputs.NetworkDns>;
    readonly domain?: pulumi.Input<string>;
    readonly mode?: pulumi.Input<string>;
    readonly mtu?: pulumi.Input<number>;
    readonly name?: pulumi.Input<string>;
    readonly routes?: pulumi.Input<pulumi.Input<inputs.NetworkRoute>[]>;
    readonly xml?: pulumi.Input<inputs.NetworkXml>;
}
